USE [master]
GO

/****** Object:  Database [POSTCH]    Script Date: 25/01/2022 20:10:32 ******/
CREATE DATABASE [POSTCH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'POSTCH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\POSTCH.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'POSTCH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\POSTCH_log.ldf' , SIZE = 860160KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [POSTCH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [POSTCH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [POSTCH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [POSTCH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [POSTCH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [POSTCH] SET ARITHABORT OFF 
GO

ALTER DATABASE [POSTCH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [POSTCH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [POSTCH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [POSTCH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [POSTCH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [POSTCH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [POSTCH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [POSTCH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [POSTCH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [POSTCH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [POSTCH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [POSTCH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [POSTCH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [POSTCH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [POSTCH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [POSTCH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [POSTCH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [POSTCH] SET RECOVERY FULL 
GO

ALTER DATABASE [POSTCH] SET  MULTI_USER 
GO

ALTER DATABASE [POSTCH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [POSTCH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [POSTCH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [POSTCH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [POSTCH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [POSTCH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [POSTCH] SET  READ_WRITE 
GO
USE POSTCH
go
DROP TABLE NEW_PLZ1 
GO

CREATE TABLE NEW_PLZ1 (
	REC_ART VARCHAR(2)
	,ONRP NUMERIC(10, 0)
	,BFSNR NUMERIC(10, 0)
	,PLZ_TYP NUMERIC(2)
	,POSTLEITZAHL NUMERIC(4)
	,PLZ_ZZ VARCHAR(2)
	,GPLZ NUMERIC(4)
	,ORTBEZ18 VARCHAR(18)
	,ORTBEZ27 VARCHAR(27)
	,KANTON VARCHAR(2)
	,SPRACHCODE NUMERIC(2)
	,SPRACHCODE_ABW NUMERIC(2)
	,BRIEFZ_DURCH NUMERIC(10)
	,GILT_AB_DAT DATE
	,PLZ_BRIEFZUST NUMERIC(6)
	,PLZ_COFF VARCHAR(1)
	) 
GO

BULK INSERT NEW_PLZ1
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\01_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

DROP TABLE NEW_PLZ2 
GO

CREATE TABLE NEW_PLZ2 (
	REC_ART VARCHAR(2)
	,ONRP NUMERIC(10)
	,LAUFNUMMER NUMERIC(6)
	,BEZTYP NUMERIC(1)
	,SPRACHCODE NUMERIC(2)
	,ORTBEZ18 VARCHAR(18)
	,ORTBEZ27 VARCHAR(27)
	)

BULK INSERT NEW_PLZ2
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\02_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

DROP TABLE NEW_COM 
GO

CREATE TABLE NEW_COM (
	REC_ART VARCHAR(2)
	,BFSNR NUMERIC(10)
	,GEMEINDENAME VARCHAR(30)
	,KANTON VARCHAR(2)
	,AGGLONR NUMERIC(5)
	)

BULK INSERT NEW_COM
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\03_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

DROP TABLE NEW_STR 
GO
CREATE TABLE NEW_STR (
	REC_ART VARCHAR(2)
	,STRID NUMERIC(13)
	,ONRP NUMERIC(10)
	,STRBEZK VARCHAR(25)
	,STRBEZL VARCHAR(60)
	,STRBEZ2K VARCHAR(25)
	,STRBEZ2L VARCHAR(60)
	,STR_LOK_TYP NUMERIC(2)
	,STRBEZ_SPC NUMERIC(2)
	,STRBEZ_COFF VARCHAR(1)
	,STR_GANZFACH VARCHAR(1)
	,STR_FACH_ONRP NUMERIC(10)
	) 
GO
BULK INSERT NEW_STR
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\04_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO
DROP TABLE NEW_STRA;
GO
CREATE TABLE NEW_STRA (
	REC_ART VARCHAR(2)
	,STRID_ALT NUMERIC(13)
	,STRID NUMERIC(13)
	,STRTYP NUMERIC(2)
	,STRBEZAK VARCHAR(25)
	,STRBEZAL VARCHAR(60)
	,STRBEZA2K VARCHAR(25)
	,STRBEZA2L VARCHAR(60)
	,STR_LOK_TYP NUMERIC(2)
	,STRBEZ_SPC NUMERIC(2)
	) 
GO

BULK INSERT NEW_STRA
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\05_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO
DROP TABLE NEW_GEB;

CREATE TABLE NEW_GEB (
	REC_ART VARCHAR(2)
	,HAUSKEY NUMERIC(13)
	,STRID NUMERIC(13)
	,HNR NUMERIC(4)
	,HNRA VARCHAR(6)
	,HNR_COFF VARCHAR(1)
	,GANZFACH VARCHAR(1)
	,FACH_ONRP NUMERIC(10)
	) 
GO

BULK INSERT NEW_GEB
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\06_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

DROP TABLE NEW_GEBA;

CREATE TABLE NEW_GEBA (
	REC_ART VARCHAR(2)
	,HAUSKEY_ALT NUMERIC(13)
	,HAUSKEY NUMERIC(13)
	,GEB_BEZ_ALT VARCHAR(25)
	,GEBTYP NUMERIC(4)
	) 
GO

BULK INSERT NEW_GEBA
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\07_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

DROP TABLE NEW_BOT_B;

CREATE TABLE NEW_BOT_B (
	REC_ART VARCHAR(2)
	,HAUSKEY NUMERIC(13)
	,APLZ NUMERIC(6)
	,BBZ_PLZ NUMERIC(6)
	,BOTENBEZ NUMERIC(6)
	,ETAPPEN_NR NUMERIC(3)
	,LAUF_NR NUMERIC(6)
	,NDEPOT VARCHAR(60)
	) 
GO

BULK INSERT NEW_BOT_B
FROM 'C:\Users\feedc\Downloads\Post_Adressdaten-20220118\08_Post_Adressdaten20220118.CSV' WITH (
		fieldterminator = ';'
		,CODEPAGE = 'RAW'
		) 
GO

SELECT TOP 10 *
FROM NEW_PLZ1

SELECT TOP 10 *
FROM NEW_PLZ2

SELECT TOP 10 *
FROM NEW_COM

SELECT TOP 10 *
FROM NEW_STR

SELECT TOP 10 *
FROM NEW_STRA

SELECT TOP 10 *
FROM NEW_GEB

SELECT TOP 10 *
FROM NEW_GEBA

SELECT TOP 10 *
FROM NEW_BOT_B
